description: Accelerating the Adoption of Open Source Assistive Technology
email: caos@googlegroups.com
github_username: a11yhood
plugins:
- jekyll-feed
- jekyll-octicons
- jekyll-readme-index
readme_index:
  enabled: true
  with_frontmatter: true
theme: minima
title: A11yhood
url: ''
