name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  GH_TOKEN: ${{ github.token }}
permissions:
  contents: write
jobs:
  Build-Site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5        
      - run: gh repo clone a11yhood/site-settings
      - run: pip install ./site-settings
      - run: python -m site_settings
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"        
          git add .
          git commit -m "generated"
          git checkout -b gh-pages
          git merge -Xtheirs main
          git push --force origin gh-pages
